### ISSUE TITLE
STV: migrate to Hafas

### ISSUE THREAD

**Issue by alexander-albers** [alexander-albers/tripkit#22]
http://appefa10.verbundlinie.at/android/ is currently no longer reachable and results in timeouts. It seems like they moved from Efa to Hafas.

The website now uses https://verkehrsauskunft.verbundlinie.at/bin/mgate.exe, while the app accesses https://app.verkehrsauskunft.at/bin/mgate.exe?mic=37cc32a073ae4f8632631e3e620b2305&mac=11d9b0dc281052e605c6a330797227d1.

**Comment by derhuerst** [comment]
FYI: Because [they have a webapp](https://verkehrsauskunft.verbundlinie.at) – just like every recently updated HAFAS endpoint –, the `mic`/`mac` parameters are not required.

**Comment by alexander-albers** [comment]
Yeah I noticed that too, that's why I wrote down both urls. But I didn't know this applies to all newer Hafas servers, thanks for the note.

**Comment by derhuerst** [comment]
BTW the necessary config for the endpoint is here:

https://github.com/public-transport/transport-apis/blob/6c800ff6b3f0670ce2a45fe0e2c600c4ac3d1359/data/at/stv-hafas-mgate.json

*Advertisement:* Do you know about the [transport-apis repo](https://github.com/public-transport/transport-apis)? We, the authors of [Travel-Status-DE-VRR](https://github.com/derf/Travel-Status-DE-VRR) (& other EFA clients?), [`kpublictransport`](https://github.com/KDE/kpublictransport) & [`hafas-client`](https://github.com/public-transport/hafas-client) agreed to deduplicate our lists of endpoint definitions into a shared repo, so that we can reduce the amount of work and benefit from more up-to-date configs. [`kpublictransport` already uses it](https://github.com/KDE/kpublictransport/blob/be289f490f2d7c5f18eeb0d9d9e2bb749f65102a/src/tools/transport-api-sync.cpp) and [`hafas-client` has started using it](https://github.com/public-transport/hafas-client/blob/ebe7c595246d31c464c27d44307b32a29a82d546/tools/pull-profile-base-data.sh).
