### ISSUE TITLE
VVO: support realtime data

### ISSUE THREAD

**Issue by alexander-albers** [alexander-albers/tripkit#75]
This api endpoint (https://webapi.vvo-online.de/tr/trips) seems to support real-time data, whereas https://efa.vvo-online.de/std3/XSLT_DM_REQUEST does not.

**Comment by derhuerst** [comment]
(sorry, somewhat unrelated comment)
@alexander-albers It would be great if you could also add this endpoint to [transport-apis](https://github.com/public-transport/transport-apis)! 🙌 This way, all consuming projects will benefit from this change as well.

**Comment by hannsadrian** [comment]
Just came across this; What do you mean by real-time data? I've been using TripKit for a while in the VVO provider network and the trips have realtime data. 

For example when a bus is expected to be three minutes late at the start of the leg but on time at it's end, this data is present. Maybe this issue is already fixed either in TripKit or by VVO in their EFA endpoint.

**Comment by alexander-albers** [comment]
Thanks, it seems like they updated their Efa endpoint to include real-time data as well. I remember checking one year ago and not seeing any delays for both trips and departures.
