### ISSUE TITLE
DB Provider uses ID as name

### ISSUE THREAD

**Issue by victorlobe** [alexander-albers/tripkit#83]
This issue is only present in DB Provider, the getUniqueShortName functions returns the ID for a station while the .id returns as slightly different id.

This is the .id output:
A=1@O=Vorstadtschule, Ratzeburg@X=10789779@Y=53700506@U=80@L=705453@

And this the .getUniqueShortName:
A=1@O=Vorstadtschule, Ratzeburg@X=10789779@Y=53700506@u=104@U=80@L=705453@

**Comment by alexander-albers** [comment]
getUniqueShortName only returns the id if the location does not have a name associated with it. In your case, it should return `Vorstadtschule`. Where did you get the Location object from?

**Comment by alexander-albers** [comment]
I actually don't know what the u number means. I always thought it could be the location's z-location (the height), but it shouldn't change in that case. According to ChatGPT, it could be related to usage, i.e. how frequently the location is used as a transit point in the public transport network. But I honestly don't know. There is another old issue related to this here: https://github.com/public-transport/hafas-client/issues/98

You can always just use the shorter form of the ids by extracting only the last part (705453). TripKit uses long format ids because in cases where they change, this gives the server enough information to resolve the location anyway.

**Comment by victorlobe** [comment]
I always forget your api is based on hafas, so I should look there first for any issues. Thanks for your help!Am 11.04.2023 um 23:10 schrieb Alexander Albers ***@***.***>:﻿
I actually don't know what the u number means. I always thought it could be the location's z-location (the height), but it shouldn't change in that case. According to ChatGPT, it could be related to usage, i.e. how frequently the location is used as a transit point in the public transport network. But I honestly don't know. There is another old issue related to this here: public-transport/hafas-client#98
You can always just use the shorter form of the ids by extracting only the last part (705453). TripKit uses long format ids because in cases where they change, this gives the server enough information to resolve the location anyway.
